### ISSUE TITLE
AttributeError: 'module' object has no attribute 'split'

### ISSUE THREAD

**Issue by SKelem** [excid3/python-apt#1]
```
% sudo pip3 install -U python-apt
Collecting python-apt
  Downloading python-apt-0.7.8.tar.bz2 (49kB)
    100% |████████████████████████████████| 53kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-3wzlbss1/python-apt/setup.py", line 11, in <module>
        string.split(parse_makefile("python/makefile")["APT_PKG_SRC"]))
    AttributeError: 'module' object has no attribute 'split'
```

So, even though I'm using pip3, the deprecated `string.split` call is in the code.

**Comment by pseudotensor** [comment]
Same issue.

python3.6 -m pip install --no-cache-dir --upgrade python-apt
Collecting python-apt
  Downloading python-apt-0.7.8.tar.bz2 (49kB)
    100% |████████████████████████████████| 51kB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9m66q1f7/python-apt/setup.py", line 11, in <module>
        string.split(parse_makefile("python/makefile")["APT_PKG_SRC"]))
    AttributeError: module 'string' has no attribute 'split'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/tmp/pip-build-9m66q1f7/python-apt/apt/__init__.py", line 2, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9m66q1f7/python-apt/setup.py", line 11, in <module>
        string.split(parse_makefile("python/makefile")["APT_PKG_SRC"]))
    AttributeError: module 'string' has no attribute 'split'

**Comment by domq** [comment]
FWIW and because Googling the error leads here, this [was fixed¹ back in 2009](https://git.launchpad.net/python-apt/diff/setup.py?id=2e4443bbd) in the [real `python-apt` package](https://launchpad.net/ubuntu/+source/python-apt), but you simply can't upgrade `python-apt` with pip.

The [issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845330) is that the `python-apt` release on [PyPI](https://pypi.python.org/pypi) is stuck at version 0.7.8 for all eternity, and [nobody cares](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845330#10). This situation will endure until someone with proper access to PyPI either updates or un-publishes `python-apt`.

¹ The `string.split` function [exists in Python 2.x](https://docs.python.org/2/library/string.html#string.split) but not  in Python 3.x, where it is only available as an [instance method of the `str` class](https://docs.python.org/3/library/stdtypes.html#str.rsplit). This made version 0.7.8 of `python-apt` incompatible with [then-new](https://en.wikipedia.org/wiki/History_of_Python#Version_3) Python 3. The release of 0.7.9 fixed that [back in March 2009](https://anonscm.debian.org/cgit/apt/python-apt.git/tree/debian/changelog?id=08dae2ec56cba3f08903ae285aec6e5f583f40fc), unfortunately PyPI stayed behind as explained above.

**Comment by linehammer** [comment]
The  **'module' object has no attribute 'split'**  error is that you're trying to call [python split](http://net-informations.com/python/file/split.htm) on the whole list of lines, and you can't split a list of strings, only a string. So, you need to split each line, not the whole thing.
